# Generated by Django 2.0.4 on 2018-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='source',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
