# Generated by Django 2.0.4 on 2018-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_appversion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='state',
            field=models.CharField(default='PENDING', max_length=60),
            preserve_default=False,
        ),
    ]
