# Generated by Django 2.0.4 on 2018-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_appversion_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='state',
            field=models.CharField(default='PENDING', max_length=60),
        ),
    ]
