# Generated by Django 2.0.4 on 2018-05-06 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20180430_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
