apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service_name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service_name}}
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: {{namespace}}-claim
      containers:
      - name: {{service_name}}
        image: {{image_name}}:{{image_version}}
        ports:
          - containerPort: {{service_port}}
        env:
        - name: SERVICE_NAME
          value: {{service_name}}
          {% for key in env_variables %}
        - name: {{key}}
          value: {{env_variables[key]}}
          {% endfor %}
        volumeMounts:
        - mountPath: "/mnt/shared-volume"
          name: pv-storage
        resources:
          limits:
            cpu: 0.2
            memory: 200Mi