apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service_name}}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service_name}}
    spec:
      containers:
      - name: {{service_name}}
        image: {{image_name}}:{{image_version}}
        ports:
          - containerPort: 80