kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{namespace}}-volume
  labels:
    type: local
    namespace_name: {{namespace}}

spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s-volumes/{{namespace}}"