kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{service_name}}-volume
  labels:
    type: local
    service_name: {{service_name}}

spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s-volumes/{{service_name}}"