kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{service_name}}-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      service_name: {{service_name}}