apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{service_name}}
    {% for key in labels %}
    {{key}}: {{labels[key]}}
    {% endfor %}
  name: {{service_name}}
spec:
  ports:
    - port: {{service_port}}
  selector:
    app: {{service_name}}
  type: ClusterIP