apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{service_name}}
  name: {{service_name}}
spec:
  ports:
    - port: {{service_port}}
  selector:
    app: {{service_name}}
  type: ClusterIP