apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{service_name}}
  name: {{service_name}}
spec:
  ports:
    # The port that this service should serve on.
    - port: {{service_port}}
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: {{service_name}}
  type: LoadBalancer