kind: ConfigMap
apiVersion: v1
metadata:
  name: {{service_name}}-config
data:
  mysqld.cnf: |-
    [mysqld]
    bind-address     = 0.0.0.0
    character-set-server=utf8
    collation-server=utf8_bin
    default-storage-engine=INNODB
    max_allowed_packet=256M
    innodb_log_file_size=2GB
    transaction-isolation=READ-COMMITTED
    datadir=/mnt/shared-volume/data/{{service_name}}
