
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service_name}}
  finalizers:
  - foregroundDeletion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service_name}}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{namespace}}-claim
        - name: config-volume
          configMap:
            name: {{service_name}}-config
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
        - name: SERVICE_NAME
          value: {{service_name}}
        - name: MYSQL_ROOT_PASSWORD
          value: root

        volumeMounts:
        - name: pv-storage
          mountPath: "/mnt/shared-volume"
        - name: config-volume
          mountPath: etc/mysql/mysql.conf.d
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
          - containerPort: 80
        env:
        - name: PMA_HOST
          value: 127.0.0.1
        resources:
          limits:
            memory: 200Mi