
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service_name}}
  finalizers:
  - foregroundDeletion
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{service_name}}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{namespace}}-claim
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
        - name: SERVICE_NAME
          value: {{service_name}}
        - name: MYSQL_ROOT_PASSWORD
          value: {{mysql_root_password}}
        volumeMounts:
          - name: pv-storage
            mountPath: /var/lib/mysql
            subPath: {{service_name}}
      {% if phpmyadmin_enabled %}
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
          - containerPort: 80
        env:
        - name: PMA_HOST
          value: 127.0.0.1
        resources:
          limits:
            memory: 200Mi
      {% endif %}