
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service_name}}
  finalizers:
  - foregroundDeletion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service_name}}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{namespace}}-claim
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
        - name: SERVICE_NAME
          value: {{service_name}}
        - name: MYSQL_ROOT_PASSWORD
          value: root

      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
          - containerPort: 80
        env:
        - name: PMA_HOST
          value: 127.0.0.1

        volumeMounts:
        - mountPath: "/mnt/shared-volume"
          name: pv-storage
        resources:
          limits:
            memory: 200Mi