apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service_name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: {{service_name}}
    servicePort: 80
  rules:
  {% if namespace == 'default' %}
  - host: '{{service_name}}.fandogh.cloud'
  {% else %}
  - host: '{{service_name}}.{{namespace}}.fandogh.cloud'
  {% endif %}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{service_name}}
          servicePort: 80