apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{service_name}}
    {% for key in labels %}
    {{key}}: {{labels[key]}}
    {% endfor %}
  name: {{service_name}}
spec:
  ports:
    - port: 80
      targetPort: 80
    - port: 3306
      targetPort: 3306
  selector:
    app: {{service_name}}
  type: ClusterIP