# Generated by Django 2.0.4 on 2018-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
